wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[2.4317590e+02 7.6027894e-01 0.0000000e+00 2.4559376e-01 5.1562500e-01\n\
    \  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00\n  0.0000000e+00\
    \ 0.0000000e+00 1.2279688e-01 1.2279688e-01]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f6fa0646bd0>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 15000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.15
    session_history: code/_session_history.ipynb
    start_time: 1668975588.157023
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 30
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 30
      - 53
      - 55
      3:
      - 1
      - 2
      - 3
      - 22
      - 23
      - 34
      - 37
      4: 3.7.15
      5: 0.13.5
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-1.], [1.], (1,), float32)
algo:
  desc: null
  value: A2C
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: 2.4726689759094212e-08
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f6fa06461d0>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.06424376821457245
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f6fba0bd8c0>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 512
normalize_advantage:
  desc: null
  value: 'False'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000.\n\
    \ -3000. -3000. -3000. -3000.], [3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000.\
    \ 3000. 3000. 3000. 3000.\n 3000. 3000.], (14,), float32)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=14,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=14, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=1, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''optimizer_class'': <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'':
    {''alpha'': 0.99, ''eps'': 1e-05, ''weight_decay'': 0}}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f6fa0646990>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1668975597096055846
tensorboard_log:
  desc: null
  value: runs/z7swokd9
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
